name: Generate docs

on:
  pull_request:
    branches:
      - develop

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Instal dependencies
        run: yarn install

      - name: Generate docs
        run: yarn docs

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
