name: Release

on: release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Instal dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Publish to NPM
        run: yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
