name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          ref: ${{ github.event.release.target_commitish }}

      - name: Install dependencies
        run: yarn install

      - name: Upgrade version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version --no-git-tag-version ${{ github.event.release.tag_name }}
          git add .
          git commit -m "Release version ${{ github.event.release.tag_name }}"
          git push HEAD:${{ github.event.release.target_commitish }}

      - name: Publish to NPM
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
