name: Release

on:
  release:
    brances:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Instal dependencies
        run: yarn install

      - name: Publish to NPM
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
